language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-27.0.2

    # The SDK version used to compile your project
    - android-21
    - android-27

    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-27"
script:
 - ./gradlew compileStagingSources jacocoTestStagingUnitTestReport testStagingUnitTest
after_success:
  - bash <(curl -s https://codecov.io/bash)
