language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-27.0.2
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-21
    - android-27

    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-27"
script:
 - ./gradlew compileStagingSources testStagingUnitTest
 - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
 - ./gradlew connectedStagingAndroidTest
 - ./gradlew jacocoTestStagingUnitTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
